### ISSUE TITLE
remove " " from your choice, user has to type "Y" in terminal, better to have it as just y. Same for the "n"

### ISSUE THREAD

**Issue by IAM-DBro** [ivanmrsulja/checkers-bot#2]
https://github.com/ivanmrsulja/checkers-bot/blob/91fd85fbab03cf083cb7d88489b0ec3368ede188/checkers.py#L80

**Comment by ivanmrsulja** [comment]
https://www.w3schools.com/python/python_strings.asp#:~:text=Strings%20are%20Arrays,access%20elements%20of%20the%20string.

**Comment by IAM-DBro** [comment]
Apologies, just confused me when Y didn't work but "Y" did.
