### ISSUE TITLE
Don't know what "end" is but it's a syntax error for me

### ISSUE THREAD

**Issue by IAM-DBro** [ivanmrsulja/checkers-bot#3]
https://github.com/ivanmrsulja/checkers-bot/blob/91fd85fbab03cf083cb7d88489b0ec3368ede188/checkers.py#L196

**Comment by ivanmrsulja** [comment]
end is an attribute for print function, it specifies the last character to be printed.

https://www.google.com/amp/s/www.geeksforgeeks.org/gfact-50-python-end-parameter-in-print/amp/

**Comment by IAM-DBro** [comment]
![image](https://user-images.githubusercontent.com/22583402/108494837-e870b880-729f-11eb-91b7-4a3905627ff8.png)

**Comment by ivanmrsulja** [comment]
Which python version are you using?This code is written in python 3.7

**Comment by IAM-DBro** [comment]
Ah that must be it, didn't set up any venv to running on 2.7
